### ISSUE TITLE
RFE: fast sync locally edited files

### ISSUE THREAD

**Issue by fommil** [Grive/grive#242]
It would be great to be able to run grive in one of two modes:
- full sync (which ignores all caches, and creates a new cache)
- compare current FS against the cache and sync only the changes (new, edited, deleted files)

cron could run the former on startup and every few hours, and the latter every 5 minutes or so.

**Comment by estomagado** [comment]
GRIVE NO LONGER MAINTAINED
PLEASE USE GRIVE2

Grive is DEPRECATED. Please refer to the newest fork Grive2.

Grive2 is here: https://github.com/vitalif/grive2
