### ISSUE TITLE
Migrate grive to the new API

### ISSUE THREAD

**Issue by gniting** [Grive/grive#313]
Now that the Google Docs API is [deprecated](https://developers.google.com/google-apps/documents-list/), any plans to update grive to work with the [new API](https://developers.google.com/drive/web/migration)?

**Comment by claenjoy** [comment]
have a look here :
https://github.com/vitalif/grive2

**Comment by gniting** [comment]
awesome and thanks!

**Comment by claenjoy** [comment]
you should sign this 
https://www.change.org/p/google-create-a-native-linux-google-drive-application
