### ISSUE TITLE
mysterious iberty dep fails

### ISSUE THREAD

**Issue by sgbeal** [Grive/grive#32]
stephan@tiny:~/cvs/grive$ cmake .
...
-- Found GDBM: /usr/lib/i386-linux-gnu/libgdbm.so
CMake Warning (dev) at libgrive/CMakeLists.txt:13 (find_package):
  A logical block opening on the line

```
/home/stephan/cvs/grive/cmake/Modules/FindIberty.cmake:16 (IF)
```

  closes on the line

```
/home/stephan/cvs/grive/cmake/Modules/FindIberty.cmake:18 (ENDIF)
```

  with mis-matching arguments.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
IBERTY_LIBRARY
    linked by target "grive" in directory /home/stephan/cvs/grive/libgrive

-- Configuring incomplete, errors occurred!

i've tried skipping that with -Wno-dev, but then cannot build:

stephan@tiny:~/cvs/grive$ make  
-- Found JSON-C: /usr/lib/i386-linux-gnu/libjson.so
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
IBERTY_LIBRARY
    linked by target "grive" in directory /home/stephan/cvs/grive/libgrive

-- Configuring incomplete, errors occurred!
make: **\* [cmake_check_build_system] Error 1

i cannot find any seemingly relevant reference to "iberty" in the package dbs for Ubuntu. What is it and where do we get it?

**Comment by ParsaAkbari** [comment]
Unfortunately installing binutils-dev doesn't seem to have solved the issue for me
Running Linux Mint 15
