### ISSUE TITLE
Syncing gdocs logic incompatible with windows client

### ISSUE THREAD

**Issue by tanisc** [Grive/grive#334]
Official windows client is creating .gdoc extention files for gdocs created in the local folder as below:
{"url": "<urltothedocument>", "email": "<emailofowner>", "resource_id": "document:<documentid>"}
If the file is deleted in the local folder, client also deletes the document in the drive. It also creates a "protocol" to open the url in the file with the default browser as the default application.
Gdrive does not compare these .gdoc files in the local directories and in the drive and deletes them from the local dir. 
This is no problem if only linux os is used, but with dual OS and using the same directories for both grive and windows client, when clients are run arbitrary, merging two processes above, grive deletes gdoc from local dir and windows deletes it from drive, causing data loss.

**Comment by tanisc** [comment]
I am new to GitHub and searched if the issue is opened before, but could not find. Please take me there if it is opened before.

**Comment by matejdro** [comment]
Ignoring gdoc files seems to help with this: `grive  --ignore "gsheet|gdoc|desktop\.ini"`

**Comment by tanisc** [comment]
I'll try to test it some time.
FYI now I use windows client with PlayOnLinux, works pretty well.

**Comment by estomagado** [comment]
GRIVE NO LONGER MAINTAINED
PLEASE USE GRIVE2

Grive is DEPRECATED. Please refer to the newest fork Grive2.

Grive2 is here: https://github.com/vitalif/grive2
