### ISSUE TITLE
The install path "/urs/local/bin" in CentOS 7 make grive unusable from crontab

### ISSUE THREAD

**Issue by lomcarlo** [Grive/grive#337]
If you install grive as instructed, the root user can not find the program if first you do not add the path /usr/local/bin to /root/.bashrc or create a link in /usr/bin

**Comment by gabrielhidasy** [comment]
It's common practice to install packages that are not from your
distribution creator in /usr/local/.

You can use the full path in Cron or one of your proposed solutions
(preferably the bashrc one), but IMHO changing the instructions to install
it under /usr would be a mistake.

Perhaps the install instructions could include information about this?

Em qui, 16 de mar de 2017 07:12, Cyberman <notifications@github.com>
escreveu:

**Comment by estomagado** [comment]
GRIVE NO LONGER MAINTAINED
PLEASE USE GRIVE2

Grive is DEPRECATED. Please refer to the newest fork Grive2.

Grive2 is here: https://github.com/vitalif/grive2
