### ISSUE TITLE
Grive ignores files of Google document type

### ISSUE THREAD

**Issue by bhargavms** [Grive/grive#338]
pdfs/epubs/jpegs etc get synced fine, but Google doc files are being ignored I dont understand why for example I get this message when I run `grive -V` 

> file "Untitled document" is a google document, ignored

**Comment by murdoxix** [comment]
Same than issues #12 and #138 !

**Comment by estomagado** [comment]
GRIVE NO LONGER MAINTAINED
PLEASE USE GRIVE2

Grive is DEPRECATED. Please refer to the newest fork Grive2.

Grive2 is here: https://github.com/vitalif/grive2
