### ISSUE TITLE
Remove outdated and not working package in debian jessie

### ISSUE THREAD

**Issue by sgitkene** [Grive/grive#339]
https://packages.debian.org/jessie/grive
this is the old grive package, which is not maintained. you can still install it with apt, but it doesn't work anymore.

**Comment by estomagado** [comment]
GRIVE NO LONGER MAINTAINED
PLEASE USE GRIVE2

Grive is DEPRECATED. Please refer to the newest fork Grive2.

Grive2 is here: https://github.com/vitalif/grive2

**Comment by sgitkene** [comment]
all I asked for was to remove the package
