### ISSUE TITLE
cd ../google_drive/

### ISSUE THREAD

**Issue by brendhadhea** [Grive/grive#340]
bash: ./grive: Is a directory
help me

**Comment by hudsantos** [comment]
You should build and install it after cloning.. Something like:

> $ git clone https://github.com/Grive/grive.git
> Cloning into 'grive'...
> remote: Counting objects: 4063, done.
> remote: Total 4063 (delta 0), reused 0 (delta 0), pack-reused 4062
> Receiving objects: 100% (4063/4063), 1.09 MiB | 438.00 KiB/s, done.
> Resolving deltas: 100% (2652/2652), done.
> Checking connectivity... done.
> $ cd grive
> $ mkdir build
> $ cd build
> $ cmake ..
> $ make -j4
> $ sudo make install

**Comment by estomagado** [comment]
GRIVE NO LONGER MAINTAINED
PLEASE USE GRIVE2

Grive is DEPRECATED. Please refer to the newest fork Grive2.

Grive2 is here: https://github.com/vitalif/grive2
