### ISSUE TITLE
Compiling and installing in Debian (LinuxMint Debian Edition)

### ISSUE THREAD

**Issue by thjwong** [Grive/grive#341]
It ran till the stage of "Install the project..." and ended in errors:

> Install the project...
>/usr/bin/cmake -P cmake_install.cmake
>-- Install configuration: "None"
>-- Installing: /mnt/data/myusername/git/grive/debian/grive/usr/bin/grive
>-- Installing: /mnt/data/myusername/git/grive/debian/grive/usr/share/man/man1/grive.1
>make[1]: Leaving directory '/mnt/data/myusername/git/grive/obj-x86_64-linux-gnu'
>   dh_installdocs -O--buildsystem=cmake -O--parallel
>   dh_installchangelogs -O--buildsystem=cmake -O--parallel
>   dh_installman -O--buildsystem=cmake -O--parallel
>   dh_pysupport -O--buildsystem=cmake -O--parallel
>dh_pysupport: This program is deprecated, you should use dh_python2 instead. Migration guide: >http://deb.li/dhs2p
>   dh_perl -O--buildsystem=cmake -O--parallel
>   dh_link -O--buildsystem=cmake -O--parallel
>   dh_compress -O--buildsystem=cmake -O--parallel
>   dh_fixperms -O--buildsystem=cmake -O--parallel
>   dh_strip -O--buildsystem=cmake -O--parallel
>   dh_makeshlibs -O--buildsystem=cmake -O--parallel
>   dh_shlibdeps -O--buildsystem=cmake -O--parallel
>dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/grive/usr/bin/grive was not linked against libz.so.1 (it uses none of the library's symbols)
>dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/grive/usr/bin/grive was not linked against libexpat.so.1 (it uses none of the library's symbols)
>dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/grive/usr/bin/grive was not linked against libboost_unit_test_framework.so.1.55.0 (it uses none of the library's symbols)
>   dh_installdeb -O--buildsystem=cmake -O--parallel
>   dh_gencontrol -O--buildsystem=cmake -O--parallel
>   dh_md5sums -O--buildsystem=cmake -O--parallel
>   dh_builddeb -O--buildsystem=cmake -O--parallel
>dpkg-deb: error: control directory has bad permissions 777 (must be >=0755 and <=0775)
>dh_builddeb: dpkg-deb --build debian/grive .. returned exit code 2
>debian/rules:4: recipe for target 'binary' failed
>make: *** [binary] Error 1
>dpkg-buildpackage: error: debian/rules binary gave error exit status 2

**Comment by estomagado** [comment]
GRIVE NO LONGER MAINTAINED
PLEASE USE GRIVE2

Grive is DEPRECATED. Please refer to the newest fork Grive2.

Grive2 is here: https://github.com/vitalif/grive2
