### ISSUE TITLE
Grive deleted files when storage reached its maximum

### ISSUE THREAD

**Issue by MaikoID** [Grive/grive#342]
Hi, I had this problem and Grive deleted files that weren't in the remote because of storage constraints, it just permanently deleted my files once I reached the storage limit, just absurd. 

Why it did that ? Why it at least haven't moved to trash instead ? Why it just inadvertently permanent erased my files ??

```
$ grive push
sync "file1.mp4" deleted in remote. deleting local
```

**Comment by estomagado** [comment]
GRIVE NO LONGER MAINTAINED
PLEASE USE GRIVE2

Grive is DEPRECATED. Please refer to the newest fork Grive2.

Grive2 is here: https://github.com/vitalif/grive2
