### ISSUE TITLE
Automatic syncing

### ISSUE THREAD

**Issue by vrossum** [Grive/grive#344]
To achieve Dropbox like syncing I use the following script
(~/gdrive is my local copy directory).
It can probably be improved, but it's a start.

#!/bin/sh
while inotifywait --recursive -e modify,delete,create ~/gdrive ; do
    grive -p ~/gdrive
    echo sleeping
    sleep 5
done

**Comment by estomagado** [comment]
GRIVE NO LONGER MAINTAINED
PLEASE USE GRIVE2

Grive is DEPRECATED. Please refer to the newest fork Grive2.

Grive2 is here: https://github.com/vitalif/grive2
