### ISSUE TITLE
User Rate Limit Exceeded

### ISSUE THREAD

**Issue by Sopor-** [Grive/grive#345]
I only have 7 small files (below 1 MB) to sync and i have 14 GB free space on Google Drive but i still get this error message `User Rate Limit Exceeded`. I have seen other third party Gdrive sync programs show this error too when uploading very big files (5GB with thousands of files). I only sync one time each day and only one file will get changed every day so it must be something else that make this error.

I'm running this on: `Linux minibian 4.4.38-v7+` and `grive version 0.5.1-dev Mar 10 2017 17:08:52`

**Comment by estomagado** [comment]
GRIVE NO LONGER MAINTAINED
PLEASE USE GRIVE2

Grive is DEPRECATED. Please refer to the newest fork Grive2.

Grive2 is here: https://github.com/vitalif/grive2
