### ISSUE TITLE
Delete remote, local deleted.  and destination folder

### ISSUE THREAD

**Issue by johnsdoes** [Grive/grive#346]
Hi, I'm new here. 
is there any way to upload only, instead of deleting local when remote files is deleted. ?
and another thing.
How to use destination -p function ?
I want to backup my inside another folder in google drive instead of backing up in root folder "my-drive" in google drive.

Thanks.

**Comment by estomagado** [comment]
GRIVE NO LONGER MAINTAINED
PLEASE USE GRIVE2

Grive is DEPRECATED. Please refer to the newest fork Grive2.

Grive2 is here: https://github.com/vitalif/grive2
