### ISSUE TITLE
Stuck at "Reading remote server file list" on first use

### ISSUE THREAD

**Issue by william-green** [Grive/grive#348]
I installed grive and everything appeared to be working until it started fetching files from Google Drive. It has been stuck on "Reading remote server file list" for nearly 10 minutes now. How long should it take to read the Google Drive file list?

Thank you.

**Comment by danielcnorris** [comment]
I am experiencing the same issue.

**Comment by yashsaxena** [comment]
Same here! But I'm on grive 2. Just bumped here...

**Comment by estomagado** [comment]
GRIVE NO LONGER MAINTAINED
PLEASE USE GRIVE2

Grive is DEPRECATED. Please refer to the newest fork Grive2.

Grive2 is here: https://github.com/vitalif/grive2
