### ISSUE TITLE
HTML files are not synced very well

### ISSUE THREAD

**Issue by arnotixe** [Grive/grive#349]
grive version 0.5.1-dev

1) adding an html file remote and running grive: the html file is ignored completely.
2) adding an html file locally and running grive: the html file is uploaded successfully.
3) renaming the uploaded html file in google drive's web interface and running grive again: the file disappears from local and this error message shows in the console:

Reading local directories
Reading remote server file list
Synchronizing files
sync "./ssml.html" deleted in remote. deleting local
sync "./ssml.html" moved to "./assml.html". moving local
Error syncing "./assml.html": boost::filesystem::rename: No such file or directory: "./ssml.html", "./assml.html"
Finished!

**Comment by estomagado** [comment]
GRIVE NO LONGER MAINTAINED
PLEASE USE GRIVE2

Grive is DEPRECATED. Please refer to the newest fork Grive2.

Grive2 is here: https://github.com/vitalif/grive2
