### ISSUE TITLE
Cant set bandwidth limit while uploading files

### ISSUE THREAD

**Issue by purvalpatel** [Grive/grive#350]
I am trying to upload 50 MB file, i want to upload this file with only 1 MB per seconds.
i am using this below commands to upload the file,
grive -s -U  1000 filename.pdf    (here, i set 1000 kbps bandwidth limit set)

Rightnow it uses my whole internet bandwidth, that is much more then what i want.

**Comment by estomagado** [comment]
GRIVE NO LONGER MAINTAINED
PLEASE USE GRIVE2

Grive is DEPRECATED. Please refer to the newest fork Grive2.

Grive2 is here: https://github.com/vitalif/grive2
