### ISSUE TITLE
Issues with building in the readme: Unmet build dependencies: debhelper zlib1g-dev

### ISSUE THREAD

**Issue by jamesray1** [Grive/grive#351]
As per the readme, I ran 
```
$ sudo apt-get install git cmake build-essential libgcrypt11-dev libyajl-dev \
>     libboost-all-dev libcurl4-openssl-dev libexpat1-dev libcppunit-dev binutils-dev
```
That installed fine.
Then I ran `git clone https://github.com/Grive/grive.git`. That worked fine.
Then `cd grive`, then `dpkg-buildpackage -j4`. That didn't work:
```
james@james-Streacom:~/grive$ dpkg-buildpackage -j4
dpkg-buildpackage: info: source package grive2
dpkg-buildpackage: info: source version 0.5.1+git20160731
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Vitaliy Filippov <vitalif@yourcmc.ru>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build grive
dpkg-checkbuilddeps: error: Unmet build dependencies: debhelper zlib1g-dev
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
james@james-Streacom:~/grive$ sudo apt-get install debhelper zlib1g-dev
```
I ran `sudo apt-get install debhelper zlib1g-dev`
That seemed to work fine, and then `dpkg-buildpackage -j4` ran fine.

The readme also doesn't tell how to run grive, you have to go to the wiki link for that.

I didn't think that I needed to do the manual build since it said `On a Debian/Ubuntu/Linux Mint you can use dpkg-buildpackage utility from dpkg-dev package to build grive`.

However, after running `dpkg-buildpackage -j4`, I couldn't run `grive` nor `grive -a` in any location, including where an old version of my Google Drive directory is.

Only after I followed the manual build instructions, opened the Google drive folder in the terminal, and ran `grive -a` did it prompt to go to the Google account oauth link and copy and paste the verification code.

**Comment by jamesray1** [comment]
So the readme could be improved to avoid confusion.

**Comment by jamesray1** [comment]
Grive synced yesterday.

**Comment by estomagado** [comment]
GRIVE NO LONGER MAINTAINED
PLEASE USE GRIVE2

Grive is DEPRECATED. Please refer to the newest fork Grive2.

Grive2 is here: https://github.com/vitalif/grive2
