### ISSUE TITLE
Fix The Readme, it is confusing!

### ISSUE THREAD

**Issue by serdasteclas** [Grive/grive#353]
I wasn't really sure if this project was active or not, the description is the same from Grive2, but there is no issue tracking in Grive 2 repo, I guess someone mirrored the Grive 2 changes but never updated... what made me believe this was the one being mantained.
Anyway, this is really confusing, please clarify on the Readme.md

**Comment by estomagado** [comment]
GRIVE NO LONGER MAINTAINED
PLEASE USE GRIVE2

Grive is DEPRECATED. Please refer to the newest fork Grive2.

Grive2 is here: https://github.com/vitalif/grive2
