### ISSUE TITLE
Dependency errors on Debian 9 (stretch)

### ISSUE THREAD

**Issue by Kurgol** [Grive/grive#354]
When I follow the instructions on the readme.md on Debian 9 (stretch) I received the following dependency errors:

user@host:~/grive2$ dpkg-buildpackage -j4
dpkg-buildpackage: info: source package grive2
dpkg-buildpackage: info: source version 0.5.1+git20160731
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Vitaliy Filippov <vitalif@yourcmc.ru>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build grive2
dpkg-checkbuilddeps: error: Unmet build dependencies: pkg-config zlib1g-dev
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)

**Comment by estomagado** [comment]
GRIVE NO LONGER MAINTAINED
PLEASE USE GRIVE2

Grive is DEPRECATED. Please refer to the newest fork Grive2.

Grive2 is here: https://github.com/vitalif/grive2
