### ISSUE TITLE
.trash doesn't work is not same file system

### ISSUE THREAD

**Issue by novazur972** [Grive/grive#355]
Hi,

In my $HOME/gdrive/ I have a bind mount.
```
$ grep /home/chris /etc/fstab
/var/images             /home/chris/gdrive/photos       none    bind    0       0
```
And if a file is localy deleted by grive in this folder (because deleted in remote), it can't be copied in .trash, so I loose it definitively : 
```
sync "/home/chris/gdrive/photos/a_trier/IMGP1079.jpg" deleted in remote. deleting local
Error syncing "/home/chris/gdrive/photos/a_trier/IMGP1079.jpg": boost::filesystem::rename: Invalid cross-device link: "/home/chris/gdrive/photos/a_trier/IMGP1079.jpg", "/home/chris/gdrive/.trash/photos/a_trier/IMGP1079.jpg"
```
Thanks

**Comment by estomagado** [comment]
GRIVE NO LONGER MAINTAINED
PLEASE USE GRIVE2

Grive is DEPRECATED. Please refer to the newest fork Grive2.

Grive2 is here: https://github.com/vitalif/grive2
