### ISSUE TITLE
Duplicated Files in Google Drive

### ISSUE THREAD

**Issue by Guiman04** [Grive/grive#356]
Google has this stupid capacity to store more than one file in the same folder with the same name.
It doesn't matter to them because they follow the file by the Id they give them. But here. you track them by the name and the Checksum. So when there are 2 files with the same folder and the same name, the program will believe that one file is the other and the other is the first and ask for update all the time. The best solution  (not the easiest) would be to track the files by the id. The other is to patch the problem by making an exception when a files repeat in the same folder.

Your program is awesome! Thank for making it!

**Comment by estomagado** [comment]
GRIVE NO LONGER MAINTAINED
PLEASE USE GRIVE2

Grive is DEPRECATED. Please refer to the newest fork Grive2.

Grive2 is here: https://github.com/vitalif/grive2
